default:
  pos: [0.15, -0.60, 0.45]
  rot: [0.5733019, -0.1278168, -0.1933737, 0.7858717]

#demo_overview_cam_impact:
#  pos: [1.75, -0.45, 0.35] #[1.60, -0.60, 0.50]
#  rot: [ 0.5241426, 0.442243, 0.4720521, 0.5539517 ] #[ 0.5609855, 0.4304593, 0.4304593, 0.5609855 ]  #[0, 0, 0, 1]

CP1:
  pos: [0.15, 0.55, 0.45]
  rot: [ 0.1845572, -0.5411509, -0.7763863, 0.2651765 ]

CP2:
  pos: [0.15, 0.52, 0.60]
  rot: [ 0.1601198, -0.4427488, -0.8431325, 0.259736 ]

CP3:
  pos: [0.60, 0.55, 0.475]
  rot: [ 0.0566408, -0.4989295, -0.8641712, 0.0327016 ]

CP4: # this was made for testing open drawer real2sim, for GR00T we will use default + CP4
  pos: [0.43, 0.55, 0.38]
  rot: [ 0, -0.5735764, -0.819152, 0 ]

CP5: # this was made for testing open drawer real2sim, for GR00T we will use default + CP4
  pos: [ 0.30, 0.55, 0.38 ]
  rot: [ 0.1422443, -0.5648625, -0.8067073, 0.0996005 ]

CP6: # this was made for testing open drawer real2sim, for GR00T we will use default + CP4
  pos: [ 0.55, 0.55, 0.38 ]
  rot: [ -0.1422443, -0.5648625, -0.8067073, -0.0996005 ]

ep_002603_cam1:
  pos: [ 0.08815308, 0.5573414, 0.53811854 ]
  rot: [ 0.19641273, -0.60020895, -0.73744156, 0.23948111 ]
ep_002603_cam2:
  pos: [ -0.13014252, -0.62850863, 0.43207309 ]
  rot: [ 0.5787572, -0.22328604, -0.31857561, 0.71672382 ]
ep_070045_cam1:
  pos: [ 0.21010001, 0.21404964, 0.18887912 ]
  rot: [ 0.20866441, -0.42927875, -0.81385086, 0.33139961 ]
ep_070045_cam2:
  pos: [ 0.16859558, -0.1901187, 0.25288203 ]
  rot: [ 0.50986659, -0.15035551, -0.31096552, 0.78786403 ]
ep_001042_cam1:
  pos: [ 0.34068829, 0.5430277, 0.32703772 ]
  rot: [ 0.16753196, -0.5371468, -0.79939062, 0.21066798 ]
ep_001042_cam2:
  pos: [ 0.2385938, -0.40790081, 0.32143831 ]
  rot: [ 0.55508485, -0.16039826, -0.25837945, 0.77420492 ]
ep_000137_cam1:
  pos: [ 0.07010116, -0.23219551, 0.36707318 ]
  rot: [ 0.31312851, -0.23141507, -0.57978243, 0.71571638 ]
ep_000137_cam2:
  pos: [ 0.29940847, 0.33112261, 0.4525249 ]
  rot: [ 0.18628773, -0.26932113, -0.85581446, 0.40043055 ]
ep_032740_cam1:
  pos: [ 0.32073444, -0.4267056, 0.40288809 ]
  rot: [ 0.42639963, -0.07752369, -0.25294611, 0.86498075 ]
ep_032740_cam2:
  pos: [ 0.47934365, 0.34131622, 0.24983321 ]
  rot: [ 0.13762955, -0.43561764, -0.86737962, 0.19735241 ]
ep_000697_cam1:
  pos: [ 0.08932064, 0.90027291, 0.61605209 ]
  rot: [ 0.24199174, -0.50077762, -0.7619479, 0.33180893 ]
ep_000697_cam2:
  pos: [ 0.0886214, -0.74412906, 0.58499128 ]
  rot: [ 0.5048017, -0.20828726, -0.36797464, 0.75258642 ]
ep_024104_cam1:
  pos: [ 0.18179218, -0.45546746, 0.48412606 ]
  rot: [ 0.49691581, -0.10193906, -0.15224302, 0.8482365 ]
ep_024104_cam2:
  pos: [ 0.31402028, 0.4306564, 0.5065152 ]
  rot: [ 0.18295113, -0.32910903, -0.81615543, 0.43829949 ]
ep_001505_cam1:
  pos: [ 0.08815308, 0.5573414, 0.53811854 ]
  rot: [ 0.19641273, -0.60020895, -0.73744156, 0.23948111 ]
ep_001505_cam2:
  pos: [ -0.0051046, -0.45445639, 0.4309217 ]
  rot: [ 0.60255768, -0.16367076, -0.23057626, 0.7463047 ]
ep_000091_cam1:
  pos: [ 0.13605253, -0.66276288, 0.3888548 ]
  rot: [ 0.49854765, -0.25295312, -0.20967432, 0.80218554 ]
ep_000091_cam2:
  pos: [ 0.20384938, 0.57193273, 0.37105995 ]
  rot: [ 0.22717911, -0.46024067, -0.80368724, 0.3010897 ]
ep_002212_cam1:
  pos: [ 0.15868941, -0.41425413, 0.41369644 ]
  rot: [ 0.43932638, -0.24583296, -0.38799659, 0.77202146 ]
ep_002212_cam2:
  pos: [ 0.14029534, 0.54126137, 0.47065198 ]
  rot: [ 0.23900645, -0.30302129, -0.78844335, 0.47896878 ]