robots:
  - name: "franka"
    type: "FrankaPandaRobotiq"
    obs_modalities: ["rgb", "proprio"]
    proprio_obs: ["joint_qpos"]
    control_freq: 15
    action_normalize: False
    controller_name: "CustomJointController" #"JointController"
    controller_config:
        arm_0:
            name: "CustomJointController" #"JointController"
            "motor_type": "position"
            control_freq: 15
            use_delta_commands: False
            use_impedances: True
            use_gravity_compensation: False,
            use_cc_compensation: False,
            Kq: [ 40, 30, 50, 35, 35, 25, 10 ]
            Kqd: [ 4, 6, 5, 5, 3, 2, 1 ]
            Kx: [ 400, 400, 400, 15, 15, 15 ]
            Kxd: [ 37, 37, 37, 2, 2, 2 ]
            command_output_limits: null
            command_input_limits: null
        gripper_0:
          name: "CustomGripperController"
          mode: "binary"
    action_type: "continuous"
    sensor_config:
      VisionSensor:
        sensor_kwargs:
          image_height: 720
          image_width: 1280
          focal_length: 2.8

#"kp": kp_values,  # Directly maps to hardware stiffness Kq
#"damping_ratio": damping_ratios, # Calculated to match hardware damping Kqd
# ---------- [GT] ----------
# "Kq": [40, 30, 50, 25, 35, 25, 10],
# "Kqd": [4, 6, 5, 5, 3, 2, 1],
# "Kx": [400, 400, 400, 15, 15, 15],
# "Kxd": [37, 37, 37, 2, 2, 2],
# ---------- [Debug] ----------
# "Kq": [40, 30, 50, 25, 35, 25, 10],
# "Kqd": [7.5, 6, 15, 5, 7.5, 2, 1],
# "Kx": [750, 750, 750, 15, 15, 15],
# "Kxd": [37, 37, 37, 2, 2, 2],
# "Kq": [10, 30, 10, 25, 10, 25, 10],
# "Kqd": [4, 6, 5, 5, 3, 2, 1],
# "Kx": [200, 200, 200, 7, 7, 7],
# "Kxd": [37, 37, 37, 2, 2, 2],
# "Kq": [10, 30, 10, 25, 5, 25, 10],
# "Kqd": [4, 6, 5, 5, 3, 2, 1],
# "Kx": [400, 400, 400, 7, 7, 7],
# "Kxd": [37, 37, 37, 2, 2, 2],
# ---------- [Mujoco sim values] ----------
# "Kq": [20, 30, 25, 25, 15, 10, 10],
# "Kqd": [1, 1.5, 1, 1, 0.5, 0.5, 0.5],
# "Kx": [100, 100, 100, 40, 40, 40],
# "Kxd": [1, 1, 1, .2, .2, .2],
# ---------- [Optimized params] ----------
# "Kq":  [40.24835708, 29.93086772, 50.32384551, 25.76151932, 34.88292241, 24.8829304, 10.78961552],
# "Kqd": [4.38372253, 5.7652592, 5.27128472, 4.7682867, 2.7671302, 2.12098393, 0.04333596],
# "Kx":  [399.13751786, 399.71884813, 399.49356886,  15.1571288, 14.54597225, 14.29382235],
# "Kxd": [37.73285257, 36.88710729, 37.03376553,  1.2875944,   1.72779607, 2.05546396],
# Optimal for green block:
# "Kq":  [10.36378298, 33.69342175, 51.16786086, 24.28141167, 5.18131875, 27.21742848, 10],
# "Kqd": [2.51456172, 8.1333822, 5.33863166, 7.76437114, 0.5, 1.66575613, 1],
# "Kx": [402.4130829, 398.36608153, 400.73736931, 14.21329666, 15.05749164, 17.55699715],
# "Kxd": [37.38221284, 37.09287685, 34.28017265,  3.49257315, 3.29102795,  1.32671746],
# Try to find optimum for second ep + block:
# "Kq": [5.0, 33.69342175, 10.0, 24.28141167, 5.18131875, 27.21742848, 10],
# "Kqd": [12.5, 8.1333822, 10.0, 7.76437114, 0.5, 1.66575613, 5.0],
# "Kx": [402.4130829, 398.36608153, 400.73736931, 14.21329666, 15.05749164, 17.55699715],
# "Kxd": [37.38221284, 37.09287685, 34.28017265, .5, .5, .5],
# "Kq":  [41.36378298, 33.69342175, 51.16786086, 24.28141167, 36.18131875, 27.21742848, 11.6409833],
# "Kqd":  [5.01456172, 8.1333822 ,7.33863166, 7.76437114, 4.29744722, 1.66575613, 1.29343471],
# "Kx": [402.4130829, 398.36608153, 400.73736931, 14.21329666, 15.05749164, 17.55699715],
# "Kxd":  [37.38221284, 37.09287685, 34.28017265, 3.4925731,  3.29102795, 6.32671746],
# ---------- [Debug FAST] ----------
#"Kq": [40, 30, 50, 35, 35, 25, 10],
#"Kqd": [4, 6, 5, 5, 3, 2, 1],
#"Kx": [400, 400, 400, 15, 15, 15],
#"Kxd": [37, 37, 37, 2, 2, 2],